/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import java.util.*;
import JDBC.EmailSender;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import JDBC.JDBCManager;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
 class Master {
    private static int transactionID;
    private static int propertyID;
    private static int agentID;
    private static int buyerID;
    private static int sellerID;
    private static String transactionDate;
    private static double price;
    private static int userID;
    

    // Getter and setter methods for transactionID
    public static int getTransactionID() {
        return transactionID;
    }

    public static void setTransactionID(int transactionID) {
        Master.transactionID = transactionID;
    }

    // Getter and setter methods for propertyID
    public static int getPropertyID() {
        return propertyID;
    }

    public static void setPropertyID(int propertyID) {
        Master.propertyID = propertyID;
    }

    // Getter and setter methods for agentID
    public static int getAgentID() {
        return agentID;
    }

    public static void setAgentID(int agentID) {
        Master.agentID = agentID;
    }

    // Getter and setter methods for buyerID
    public static int getBuyerID() {
        return buyerID;
    }

    public static void setBuyerID(int buyerID) {
        Master.buyerID = buyerID;
    }

    // Getter and setter methods for sellerID
    public static int getSellerID() {
        return sellerID;
    }

    public static void setSellerID(int sellerID) {
        Master.sellerID = sellerID;
    }

    // Getter and setter methods for transactionDate
    public static String getTransactionDate() {
        return transactionDate;
    }

    public static void setTransactionDate(String transactionDate) {
        Master.transactionDate = transactionDate;
    }

    // Getter and setter methods for price
    public static double getPrice() {
        return price;
    }

    public static void setPrice(double price) {
        Master.price = price;
    }
    
    // Getter and setter methods for userID
    public static int getUserID() {
        return userID;
    }

    public static void setUserID(int userID) {
        Master.userID = userID;
    }
}


/**
 *
 * @author kartikdhyani
 */
public class Login extends javax.swing.JFrame {
    int num;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_user = new javax.swing.JFrame();
        email = new javax.swing.JTextField();
        newuser = new javax.swing.JTextField();
        usertype = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        newpasscode = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        forgot_password = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        forgot_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Homepage = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Posting = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        adrress = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        desc = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Transactions = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        passcode = new javax.swing.JPasswordField();
        userid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        create_user.setMinimumSize(new java.awt.Dimension(588, 360));
        create_user.setSize(new java.awt.Dimension(588, 360));
        create_user.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        create_user.getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 61, 167, -1));
        create_user.getContentPane().add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 119, 167, -1));

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer/Seller", "Agent", "Builder" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        create_user.getContentPane().add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 90, 166, -1));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        create_user.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 201, -1, -1));
        create_user.getContentPane().add(newpasscode, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 160, 170, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        create_user.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 64, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("User Type");
        create_user.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 93, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("User Name");
        create_user.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 122, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Password");
        create_user.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 163, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        create_user.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        forgot_password.setMinimumSize(new java.awt.Dimension(399, 360));
        forgot_password.setSize(new java.awt.Dimension(399, 360));

        jPanel3.setMinimumSize(new java.awt.Dimension(588, 360));
        jPanel3.setPreferredSize(new java.awt.Dimension(588, 360));
        jPanel3.setSize(new java.awt.Dimension(588, 360));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgot_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_emailActionPerformed(evt);
            }
        });
        jPanel3.add(forgot_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 69, 192, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter email");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 91, -1));

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 191, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 104, 192, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter otp");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, 72, -1));

        jButton6.setText("verify");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 69, -1, -1));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 104, 72, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 192, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Enter new password");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        javax.swing.GroupLayout forgot_passwordLayout = new javax.swing.GroupLayout(forgot_password.getContentPane());
        forgot_password.getContentPane().setLayout(forgot_passwordLayout);
        forgot_passwordLayout.setHorizontalGroup(
            forgot_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        forgot_passwordLayout.setVerticalGroup(
            forgot_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Homepage.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Homepage.setMinimumSize(new java.awt.Dimension(500, 500));
        Homepage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(588, 360));
        jPanel4.setPreferredSize(new java.awt.Dimension(588, 360));
        jPanel4.setSize(new java.awt.Dimension(588, 360));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 43, 175, 31));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 47, -1, -1));

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jPanel4.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 28, -1, -1));

        jButton7.setText("Submit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 86, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 586, 344));

        jLabel5.setText("Welcome ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 10, -1, -1));

        jButton8.setText("Post property");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel8.setText("BHK");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        Homepage.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPasswordField1.setText("jPasswordField1");

        Posting.setMinimumSize(new java.awt.Dimension(500, 360));
        Posting.setSize(new java.awt.Dimension(500, 360));
        Posting.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        Posting.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 15, -1, -1));
        Posting.getContentPane().add(adrress, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 50, 98, -1));
        Posting.getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 91, 98, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        Posting.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 132, -1, -1));
        Posting.getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 189, 98, -1));

        jButton9.setText("Post");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Posting.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 274, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        Posting.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 53, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        Posting.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 94, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Size");
        Posting.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 135, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Description");
        Posting.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 192, -1, -1));

        jButton11.setText("Transaction Details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Posting.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 274, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        Posting.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        Transactions.setMinimumSize(new java.awt.Dimension(497, 353));
        Transactions.setSize(new java.awt.Dimension(497, 353));
        Transactions.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Transactions");
        Transactions.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 18, -1, -1));

        jButton10.setText("Show transactions");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Transactions.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 53, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Transactions.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 82, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        Transactions.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 500, 490));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 388));
        setPreferredSize(new java.awt.Dimension(500, 388));
        setSize(new java.awt.Dimension(500, 388));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Username");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Password");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        passcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passcodeActionPerformed(evt);
            }
        });
        getContentPane().add(passcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 108, -1));

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        getContentPane().add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 108, -1));

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton2.setText("create user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jButton4.setText("forgot password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 333, 130, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_209124760_sEIPfgAurKyrJMIUmdg2cLyiDdxZ8dBr.jpeg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/real_estate";
            String username = "root";
            String password = "kartikkartik";
            
            JDBCManager jdbcManager = new JDBCManager(url, username, password);
            
            // Example usage:
            String query = "SELECT userid, password " +
                    "FROM userdetails " +
                    "WHERE username = '" + userid.getText() + "' AND password = '" + passcode.getText() + "'";
            
            ResultSet resultSet = jdbcManager.executeQuery(query);
            
            if(resultSet.next())
            {
                System.out.println("Done!");
                int id=resultSet.getInt("userid");
                
                
                Master.setUserID(id);
                String query2 = "SELECT usertype " +
                "FROM userdetails " +
                "WHERE userid = '" + id + "'";

            
            ResultSet resultSet2 = jdbcManager.executeQuery(query2);
            resultSet2.next();
            String type=resultSet2.getString("usertype");
            jLabel7.setText(type);
            switch(type)
            {
                case "Buyer/Seller":
                    Homepage.setVisible(true);
                    jLabel5.setText("Welcome "+userid.getText().toString());
                    break;
                case "Agent":
                    Posting.setVisible(true);
                    break;
                case "Builder":
                    Posting.setVisible(true);
                    break;
                    
            }
                
               
              

               
                
            }
            jdbcManager.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    create_user.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
    
    Random rand = new Random();
    String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
    String password = "kartikkartik";
    
    JDBCManager jdbcManager = new JDBCManager(url, username, password);
    int userid=rand.nextInt(1000, 8000);;
    
    String query1 = "select * from userdetails where userid="+userid;
            
            ResultSet resultSet = jdbcManager.executeQuery(query1);
    while (resultSet.next())
    {
        System.out.println(userid);
     userid=rand.nextInt(1000, 8000);
    
     query1 = "select * from userdetails where userid="+userid;
            
             resultSet = jdbcManager.executeQuery(query1);
    
    }
    
    // Example usage:
    String query = "insert into userdetails values" +
       "(" +userid  + ",'" + newuser.getText() + "','" + email.getText() + "','" + newpasscode.getText() + "','" + usertype.getSelectedItem().toString() + "')";
    
    int rowsAffected = jdbcManager.executeUpdate(query);
    
    if (rowsAffected > 0) {
        Homepage.setVisible(true);
    }
    
    jdbcManager.closeConnection();
} catch (SQLException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        forgot_password.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void forgot_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgot_emailActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
    String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
    String password = "kartikkartik";
    
    JDBCManager jdbcManager = new JDBCManager(url, username, password);
    
    // Example usage:
    String emailToVerify = forgot_email.getText();
    String query = "SELECT COUNT(*) FROM userdetails WHERE email = '" + emailToVerify + "'";
    
    ResultSet resultSet = jdbcManager.executeQuery(query);
    
    if (resultSet.next()) {
        int count = resultSet.getInt(1);
        if (count > 0) {
            // Email exists
            jLabel4.setText("Email exits");
            EmailSender obj=new EmailSender("#####.######@#########.edu.in","##########");
            Random rand=new Random();
            num=rand.nextInt(1000,8000);
            String otp=String.valueOf(num);
            obj.sendEmail(emailToVerify, "Reset password", otp);
        } else {
            // Email does not exist
            jLabel4.setText("Email does not exist");
            
        }
    }
    
    jdbcManager.closeConnection();
} catch (SQLException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String otp=String.valueOf(num);
        
        if (otp.equals(jTextField5.getText()))
        {
            
            try {
    String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
    String password = "kartikkartik";
    
    JDBCManager jdbcManager = new JDBCManager(url, username, password);
    
    // Example usage:
    String userEmail = "user@example.com";
    String newPassword = "new_password";
    String query = "UPDATE userdetails SET password = '" + jTextField6.getText() + "' WHERE email = '" + forgot_email.getText() + "'";
    
    int rowsAffected = jdbcManager.executeUpdate(query);
    
    System.out.println(rowsAffected + " row(s) updated.");
    
    jdbcManager.closeConnection();
} catch (SQLException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
}
        }
        else
        {
            jLabel4.setText("Invalid otp");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void passcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passcodeActionPerformed

// Custom renderer class for rendering buttons in JTable
class ButtonRenderer extends JButton implements TableCellRenderer {
    public ButtonRenderer() {
        setOpaque(true);
        addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("True");
                // Handle button click action here
                jLabel5.setText("Done!");
            }
        });
    }
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        // Set button text
        setText((value == null) ? "" : value.toString());
        return this;
    }
}
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
    String password = "kartikkartik";

    String addr = jTextField7.getText().trim();
    int sliderValue = jSlider1.getValue() * 100000;
    String sizeValue = jComboBox1.getSelectedItem().toString();

    try (Connection connection = DriverManager.getConnection(url, username, password)) {
        String query = "SELECT * FROM propertydetails WHERE address = ? AND price < ? AND size = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, addr);
            preparedStatement.setInt(2, sliderValue);
            preparedStatement.setString(3, sizeValue);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.setRowCount(0);
                tableModel.setColumnCount(0);

                tableModel.addColumn("PropertyID");
                tableModel.addColumn("Address");
                tableModel.addColumn("Price");
                tableModel.addColumn("Size");
                tableModel.addColumn("Description");
                tableModel.addColumn("UserID");
                tableModel.addColumn("Button");
                

                while (resultSet.next()) {
                    Object[] rowData = {
                        resultSet.getInt("PropertyID"),
                        resultSet.getString("Address"),
                        resultSet.getDouble("Price"),
                        resultSet.getDouble("Size"),
                        resultSet.getString("Description"),
                        resultSet.getInt("UserID"),
                        "Buy"
                    };
                    tableModel.addRow(rowData);
                }
            }
        }
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new ButtonRenderer());
        // Add ActionListener to the JTable
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = jTable1.getColumnModel().getColumnIndex("Button");
                int row = jTable1.rowAtPoint(e.getPoint());
                if (row >= 0 && column >= 0 && jTable1.getModel().getValueAt(row, column).toString().equals("Buy")) {
                    // Handle button click action here
                    handleBuyButton((int) jTable1.getValueAt(row, 0), (int) jTable1.getValueAt(row, 5), (double) jTable1.getValueAt(row, 2));
                }
            }
        });
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}

// Assuming this method is declared within the class
private void handleBuyButton(int propertyID, int sellerID, double price) {
   String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
    String password = "kartikkartik";

    try (Connection connection = DriverManager.getConnection(url, username, password)) {
        // Inserting transaction into transactiondetails table
        int transactionID;
        boolean uniqueIDFound = false;
        do {
            transactionID = (int) (Math.random() * 1000) + 1;
            try (PreparedStatement checkStatement = connection.prepareStatement("SELECT COUNT(*) AS count FROM transactiondetails WHERE TransactionID = ?")) {
                checkStatement.setInt(1, transactionID);
                try (ResultSet resultSet = checkStatement.executeQuery()) {
                    if (resultSet.next() && resultSet.getInt("count") == 0) {
                        uniqueIDFound = true;
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } while (!uniqueIDFound);

        java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());
        String insertQuery = "INSERT INTO transactiondetails (TransactionID, PropertyID, BuyerID, SellerID, TransactionDate, Price) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
            preparedStatement.setInt(1, transactionID);
            preparedStatement.setInt(2, propertyID);
            preparedStatement.setInt(3, Master.getUserID()); // Assuming BuyerID is obtained from Master class
            preparedStatement.setInt(4, sellerID);
            preparedStatement.setDate(5, currentDate);
            preparedStatement.setDouble(6, price);
            preparedStatement.executeUpdate();
            System.out.println("Insertion into transactiondetails completed successfully!");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
           
            
    

    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Posting.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {                                         
            // TODO add your handling code here:
            Random rand = new Random();
            String url = "jdbc:mysql://localhost:3306/real_estate";
            String username = "root";
            String password = "kartikkartik";
            
            JDBCManager jdbcManager = new JDBCManager(url, username, password);
            int propid=rand.nextInt(1000, 8000);;
            
            String query1 = "select * from propertydetails where PropertyID="+propid;
            
            ResultSet resultSet = jdbcManager.executeQuery(query1);
            try {
                while (resultSet.next())
                {
                    System.out.println(propid);
                    propid=rand.nextInt(1000, 8000);
                    
                    query1 = "select * from propertydetails where PropertyID="+propid;
                    
                    resultSet = jdbcManager.executeQuery(query1);
                    
                }   } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            String query2 = "INSERT INTO propertydetails VALUES (" + propid + ",'" + adrress.getText().toString() + "'," + price.getText() + ",'" + jComboBox2.getSelectedItem() + "','" + desc.getText() + "'," + Master.getUserID() + ")";
            
            jdbcManager.executeUpdate(query2);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
            // TODO add your handling code here:
            String url = "jdbc:mysql://localhost:3306/real_estate";
    String username = "root";
     String password = "kartikkartik";

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("TransactionID");
        model.addColumn("PropertyID");
        model.addColumn("BuyerID");
        model.addColumn("SellerID");
        model.addColumn("TransactionDate");
        model.addColumn("Price");
        jTable2.setModel(model);

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            String query = "SELECT * FROM transactiondetails where BuyerID="+Master.getUserID()+" or SellerID="+Master.getUserID();
            try (PreparedStatement preparedStatement = connection.prepareStatement(query);
                 ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    int transactionID = resultSet.getInt("TransactionID");
                    int propertyID = resultSet.getInt("PropertyID");
                    int buyerID = resultSet.getInt("BuyerID");
                    int sellerID = resultSet.getInt("SellerID");
                    String transactionDate = resultSet.getString("TransactionDate");
                    double price = resultSet.getDouble("Price");

                    model.addRow(new Object[]{transactionID, propertyID, buyerID, sellerID, transactionDate, price});
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Transactions.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Homepage;
    private javax.swing.JFrame Posting;
    private javax.swing.JFrame Transactions;
    private javax.swing.JTextField adrress;
    private javax.swing.JFrame create_user;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField forgot_email;
    private javax.swing.JFrame forgot_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JPasswordField newpasscode;
    private javax.swing.JTextField newuser;
    private javax.swing.JPasswordField passcode;
    private javax.swing.JTextField price;
    private javax.swing.JTextField userid;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
